#!/usr/bin/expect -f

source ./utils.exp
source ./invalid_IP_list.exp

set timeout 10
spawn java -jar ./../../infotecs-1.0.jar

safe_expect "Do you want to change these parameters? (y/n)"
send "n\r"

safe_expect "Connected!"
send "\r"

safe_expect "Menu:"
send "3\r"

safe_expect "Enter IP"
send "222.222.222.222\r"
safe_expect "Doesn't find domain by given IP"
send "\r"

safe_expect "Menu:"
send "3\r"
invalid_IP_list

safe_expect "Enter.*IP" 1
send "abc.def.ghi.jkl\r"
safe_expect "Wrong input. Enter valid.*IP!" 1

send "0\r0\r"

expect eof