#!/usr/bin/expect -f

source ./utils.exp

set timeout 10
spawn java -jar ./../../infotecs-1.0.jar

safe_expect "Do you want to change these parameters? (y/n)"
send "y\r"

safe_expect "Select what do you want to change"
send "1\r"

safe_expect "Enter IP"
send "1.1.1.1\r"
safe_expect ".*1.1.1.1.*" 1
send "2\r"

safe_expect "Enter Port"
send "11\r"
safe_expect ".*11.*" 1
send "3\r"

safe_expect "Enter User"
send "skebob\r"
safe_expect ".*skebob.*" 1
send "4\r"

safe_expect "Enter Password"
send "yomapass\r"
safe_expect ".*yomapass.*" 1
send "5\r"

safe_expect "Enter Local directory"
send "localdir\r"
safe_expect ".*localdir.*" 1
send "6\r"

safe_expect "Enter File path"
send "filepath\r"
safe_expect ".*filepath.*" 1
send "7\r"

safe_expect "Enter IP"
send "1.2.3.4\r"
safe_expect "Enter Port"
send "1234\r"
safe_expect "Enter User"
send "testuser\r"
safe_expect "Enter Password"
send "testpass\r"
safe_expect "Enter Local directory"
send "testdir\r"
safe_expect "Enter File path"
send "testpath\r"

expect {
    -re ".*1.2.3.4.*1234.*testuser.*testpass.*testdir.*testpath.*" {
    exit 0
    }
    timeout {
    exit 1
    }
}

expect eof